// <auto-generated />
namespace TravelAnywhere.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class cascadingdelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascadingdelete));
        
        string IMigrationMetadata.Id
        {
            get { return "202108242358499_cascading delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
